### ISSUE TITLE
Implement the Safegaze new design

### ISSUE THREAD

**Issue by cemsertkaya** [AsilHQ/Asil-ios#40]

**Comment by cemsertkaya** [comment]
https://www.figma.com/file/XrtzqVfC2W22lIA5LxyPSp/SafGaze-%26-Asil?type=design&node-id=2201-242&mode=design&t=3HPU0Edy9eFZLCeK-0

**Comment by HMZahir** [comment]
![Image](https://github.com/AsilHQ/Asil-ios/assets/89986591/ad98f908-5b88-4b7b-b488-8938d67bd70e)



![Image](https://github.com/AsilHQ/Asil-ios/assets/89986591/397e9293-56cb-4c8e-b58f-e80e3550c8da)

**Comment by nizamuddin** [comment]
@cemsertkaya Please use this link https://safegaze.com/support-safegaze/ in "Support this project"
