### ISSUE TITLE
Safegaze popup localizations

### ISSUE THREAD

**Issue by cemsertkaya** [AsilHQ/Asil-ios#42]

**Comment by cemsertkaya** [comment]
"safegaze.popup.report.title1" = "Please report any bugs or suggestions to ";
"safegaze.popup.report.title2" = "this form";
 "safegaze.popup.support.title" = "Support this project";
    "safegaze.popup.woman.title" = "I am Woman";
    "safegaze.popup.man.title" = "I am Man";
    "safegaze.popup.comingsoon.title" = "Coming Soon";
    "safegaze.popup.gendermode.title" = "Gender Mode";
    "safegaze.popup.sinfulacts.title" = "Sinful acts avoided";
    "safegaze.popup.thispage.title" = "This Page";
    "safegaze.popup.lifetime.title" = "Lifetime";
    "safegaze.popup.alwayspurify.title" = "Always Purify";
    "safegaze.popup.neverpurify.title" = "Never Purify"
    "safegaze.popup.safegazeup.title" = "Safegaze UP";
    "safegaze.popup.imageblur.title" = "Image Blur Intensity";
    "safegaze.popup.takecontrol.title" = "Take control of your digital space with our Ad Blocker and Image Purificator extension combo. Savegaze will save your eyes from singul act.";
    "safegaze.popup.turnon.title" = "Turn on SafeGaze"

**Comment by cemsertkaya** [comment]
![Image](https://github.com/AsilHQ/Asil-ios/assets/52299445/202ac2c6-60fc-4e52-a368-3c6a5fd034eb)

These are the languages for iOS app

**Comment by nizamuddin** [comment]
what will be the format? Just give you separate translation file?

**Comment by nizamuddin** [comment]
Arabic
```swift
"safegaze_popup_report_title1" = "يرجى الإبلاغ عن أي أخطاء أو اقتراحات إلى";
"safegaze_popup_report_title2" = "هذا النموذج";
"safegaze_popup_support_title" = "دعم هذا المشروع";
"safegaze_popup_woman_title" = "أنا امرأة";
"safegaze_popup_man_title" = "أنا رجل";
"safegaze_popup_comingsoon_title" = "قريبا";
"safegaze_popup_gendermode_title" = "وضع الجنس";
"safegaze_popup_sinfulacts_title" = "أعمال الخطيئة المتجنبة";
"safegaze_popup_thispage_title" = "هذه الصفحة";
"safegaze_popup_lifetime_title" = "العمر كله";
"safegaze_popup_alwayspurify_title" = "تنقية دائما";
"safegaze_popup_neverpurify_title" = "لاتنقية أبدا";
"safegaze_popup_safegazeup_title" = "سيفجاز لأعلى";
"safegaze_popup_imageblur_title" = "شدة ضبابية الصورة";
"safegaze_popup_takecontrol_title" = "تحكم في مساحتك الرقمية مع مزيج امتداد مانع الإعلانات ومنقي الصور. سيوفر سيفجاز عينيك من فعل الغناء.";
"safegaze_popup_turnon_title" = "تفعيل سيفجاز";

``` 
Turkish
```swift
"safegaze_popup_report_title1" = "Lütfen herhangi bir hata veya öneriyi şu adrese bildirin";
"safegaze_popup_report_title2" = "bu form";
"safegaze_popup_support_title" = "Bu projeyi destekleyin";
"safegaze_popup_woman_title" = "Ben Kadınım";
"safegaze_popup_man_title" = "Ben Erkeğim";
"safegaze_popup_comingsoon_title" = "Yakında";
"safegaze_popup_gendermode_title" = "Cinsiyet Modu";
"safegaze_popup_sinfulacts_title" = "Kaçınılan günah işleri";
"safegaze_popup_thispage_title" = "Bu Sayfa";
"safegaze_popup_lifetime_title" = "Ömür boyu";
"safegaze_popup_alwayspurify_title" = "Her Zaman Arındır";
"safegaze_popup_neverpurify_title" = "Asla Arındırma";
"safegaze_popup_safegazeup_title" = "SafeGaze YUKARI";
"safegaze_popup_imageblur_title" = "Resim Bulanıklık Yoğunluğu";
"safegaze_popup_takecontrol_title" = "Reklam Engelleyicimiz ve Resim Arındırıcı eklentimizle dijital alanınızın kontrolünü ele alın. SafeGaze, gözlerinizi tek bir hareketten koruyacak.";
"safegaze_popup_turnon_title" = "SafeGaze'i Aç";

```
Russian 
```swift
"safegaze_popup_report_title1" = "Пожалуйста, сообщите о любых ошибках или предложениях на";
"safegaze_popup_report_title2" = "эту форму";
"safegaze_popup_support_title" = "Поддержать этот проект";
"safegaze_popup_woman_title" = "Я Женщина";
"safegaze_popup_man_title" = "Я Мужчина";
"safegaze_popup_comingsoon_title" = "Скоро будет";
"safegaze_popup_gendermode_title" = "Режим пола";
"safegaze_popup_sinfulacts_title" = "Избегаемые греховные поступки";
"safegaze_popup_thispage_title" = "Эта страница";
"safegaze_popup_lifetime_title" = "Всю жизнь";
"safegaze_popup_alwayspurify_title" = "Всегда очищать";
"safegaze_popup_neverpurify_title" = "Никогда не очищать";
"safegaze_popup_safegazeup_title" = "SafeGaze ВВЕРХ";
"safegaze_popup_imageblur_title" = "Интенсивность размытия изображения";
"safegaze_popup_takecontrol_title" = "Возьмите под контроль свое цифровое пространство с помощью нашего комбо расширений блокировщика рекламы и очистителя изображений. SafeGaze защитит ваши глаза от единичного действия.";
"safegaze_popup_turnon_title" = "Включить SafeGaze";

```

**Comment by cemsertkaya** [comment]
We have a problem @nizamuddin, "Take control of your digital space with our Ad Blocker and Image Purificator extension combo. Savegaze will save your eyes from singul act."; there is a typo in figma I guess, Isn't it sinful instead of singul?

**Comment by cemsertkaya** [comment]
I saw the mistake in turkish localization
I think we need to update this sentences for other languages too.

**Comment by nizamuddin** [comment]
Yes we need to change it to 
<p>

Enhance your online experience with Safegaze, our Image Purificator extension that shields your vision from inappropriate content.
</p>
</details>

**Comment by cemsertkaya** [comment]
OK, do you want me to make google translate for arabic russian en turkish?

**Comment by nizamuddin** [comment]
Yes, please. That will be great. Or you can do translation with ChatGPT.

**Comment by cemsertkaya** [comment]
OK, I'll make other languages to

**Comment by cemsertkaya** [comment]
I'm taking this task then
